package com.plexobject.testplayer.generator;

import com.plexobject.testplayer.ApplicationContext;
import com.plexobject.testplayer.generator.SequenceGenerator;
import junit.framework.TestCase;

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL. Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for informations about the tool, the licence and the authors.
 */


public class SequenceGeneratorTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.generator.SequenceGenerator sequencegenerator = null;
  // JUnitDoclet end class
  
  public SequenceGeneratorTest(String name) {
    // JUnitDoclet begin method SequenceGeneratorTest
    super(name);
    // JUnitDoclet end method SequenceGeneratorTest
  }
  
  public com.plexobject.testplayer.generator.SequenceGenerator createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.generator.SequenceGenerator(new ApplicationContext());
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    sequencegenerator = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    sequencegenerator = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(SequenceGeneratorTest.class);
    // JUnitDoclet end method testcase.main
  }
}
