package com.plexobject.testplayer.plugin.test;

import junit.framework.TestSuite;
import com.plexobject.testplayer.plugin.test.unit.UnitSuite;
import com.plexobject.testplayer.plugin.test.functional.FunctionalSuite;
import com.plexobject.testplayer.plugin.test.integration.IntegrationSuite;
import com.plexobject.testplayer.plugin.test.regression.RegressionSuite;


// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class TestSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // JUnitDoclet end class
  
  public static TestSuite suite() {
    
    TestSuite suite;
    
    suite = new TestSuite("com.plexobject.testplayer.plugin.test");
    
    
    suite.addTest(com.plexobject.testplayer.plugin.test.unit.UnitSuite.suite());
    suite.addTest(com.plexobject.testplayer.plugin.test.functional.FunctionalSuite.suite());
    suite.addTest(com.plexobject.testplayer.plugin.test.integration.IntegrationSuite.suite());
    suite.addTest(com.plexobject.testplayer.plugin.test.regression.RegressionSuite.suite());
    
    
    // JUnitDoclet begin method suite
    // JUnitDoclet end method suite
    
    return suite;
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testsuite.main
    junit.textui.TestRunner.run(suite());
    // JUnitDoclet end method testsuite.main
  }
}
