package com.plexobject.testplayer;

import junit.framework.TestSuite;
import com.plexobject.testplayer.aspects.AspectsSuite;
import com.plexobject.testplayer.events.EventsSuite;
import com.plexobject.testplayer.fitnesse.FitnesseSuite;
import com.plexobject.testplayer.marshal.MarshalSuite;
import com.plexobject.testplayer.plugin.PluginSuite;
import com.plexobject.testplayer.tree.TreeSuite;
import com.plexobject.testplayer.util.UtilSuite;
import com.plexobject.testplayer.visitor.VisitorSuite;


// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class TestplayerSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // JUnitDoclet end class
  
  public static TestSuite suite() {
    
    TestSuite suite;
    
    suite = new TestSuite("com.plexobject.testplayer");
    
    suite.addTestSuite(com.plexobject.testplayer.MethodEntryTest.class);
    suite.addTestSuite(com.plexobject.testplayer.ApplicationContextTest.class);
    
    suite.addTest(com.plexobject.testplayer.aspects.AspectsSuite.suite());
    suite.addTest(com.plexobject.testplayer.events.EventsSuite.suite());
    suite.addTest(com.plexobject.testplayer.fitnesse.FitnesseSuite.suite());
    suite.addTest(com.plexobject.testplayer.marshal.MarshalSuite.suite());
    suite.addTest(com.plexobject.testplayer.plugin.PluginSuite.suite());
    suite.addTest(com.plexobject.testplayer.tree.TreeSuite.suite());
    suite.addTest(com.plexobject.testplayer.util.UtilSuite.suite());
    suite.addTest(com.plexobject.testplayer.visitor.VisitorSuite.suite());
    
    
    // JUnitDoclet begin method suite
    // JUnitDoclet end method suite
    
    return suite;
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testsuite.main
    junit.textui.TestRunner.run(suite());
    // JUnitDoclet end method testsuite.main
  }
}
