package com.plexobject.testplayer.aspects;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.aspects.CallInterceptorAspect;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CallInterceptorAspectTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.aspects.CallInterceptorAspect callinterceptoraspect = null;
  // JUnitDoclet end class
  
  public CallInterceptorAspectTest(String name) {
    // JUnitDoclet begin method CallInterceptorAspectTest
    super(name);
    // JUnitDoclet end method CallInterceptorAspectTest
  }
  
  public com.plexobject.testplayer.aspects.CallInterceptorAspect createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.aspects.CallInterceptorAspect();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    callinterceptoraspect = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    callinterceptoraspect = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testTraceMethod() throws Exception {
    // JUnitDoclet begin method traceMethod
    // JUnitDoclet end method traceMethod
  }
  
  public void testCleanStack() throws Exception {
    // JUnitDoclet begin method cleanStack
    // JUnitDoclet end method cleanStack
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CallInterceptorAspectTest.class);
    // JUnitDoclet end method testcase.main
  }
}
