package com.plexobject.testplayer.fitnesse;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.fitnesse.ArrayFixtureWrapper;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ArrayFixtureWrapperTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.fitnesse.ArrayFixtureWrapper arrayfixturewrapper = null;
  // JUnitDoclet end class
  
  public ArrayFixtureWrapperTest(String name) {
    // JUnitDoclet begin method ArrayFixtureWrapperTest
    super(name);
    // JUnitDoclet end method ArrayFixtureWrapperTest
  }
  
  public com.plexobject.testplayer.fitnesse.ArrayFixtureWrapper createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.fitnesse.ArrayFixtureWrapper();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    arrayfixturewrapper = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    arrayfixturewrapper = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testQuery() throws Exception {
    // JUnitDoclet begin method query
    // JUnitDoclet end method query
  }
  
  public void testGetBackend() throws Exception {
    // JUnitDoclet begin method getBackend
    // JUnitDoclet end method getBackend
  }
  
  public void testSet() throws Exception {
    // JUnitDoclet begin method set
    // JUnitDoclet end method set
  }
  
  public void testAdd() throws Exception {
    // JUnitDoclet begin method add
    // JUnitDoclet end method add
  }
  
  public void testGetTargetClass() throws Exception {
    // JUnitDoclet begin method getTargetClass
    // JUnitDoclet end method getTargetClass
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ArrayFixtureWrapperTest.class);
    // JUnitDoclet end method testcase.main
  }
}
