package com.plexobject.testplayer.fitnesse;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.fitnesse.WikiTableWriter;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class WikiTableWriterTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.fitnesse.WikiTableWriter wikitablewriter = null;
  // JUnitDoclet end class
  
  public WikiTableWriterTest(String name) {
    // JUnitDoclet begin method WikiTableWriterTest
    super(name);
    // JUnitDoclet end method WikiTableWriterTest
  }
  
  public com.plexobject.testplayer.fitnesse.WikiTableWriter createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.fitnesse.WikiTableWriter();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    wikitablewriter = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    wikitablewriter = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testStartNode() throws Exception {
    // JUnitDoclet begin method startNode
    // JUnitDoclet end method startNode
  }
  
  public void testSetValue() throws Exception {
    // JUnitDoclet begin method setValue
    // JUnitDoclet end method setValue
  }
  
  public void testAddAttribute() throws Exception {
    // JUnitDoclet begin method addAttribute
    // JUnitDoclet end method addAttribute
  }
  
  public void testEndNode() throws Exception {
    // JUnitDoclet begin method endNode
    // JUnitDoclet end method endNode
  }
  
  public void testFlush() throws Exception {
    // JUnitDoclet begin method flush
    // JUnitDoclet end method flush
  }
  
  public void testClose() throws Exception {
    // JUnitDoclet begin method close
    // JUnitDoclet end method close
  }
  
  public void testUnderlyingWriter() throws Exception {
    // JUnitDoclet begin method underlyingWriter
    // JUnitDoclet end method underlyingWriter
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(WikiTableWriterTest.class);
    // JUnitDoclet end method testcase.main
  }
}
