package com.plexobject.testplayer.fitnesse;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.fitnesse.WikiTableSetupFixture;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class WikiTableSetupFixtureTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.fitnesse.WikiTableSetupFixture wikitablesetupfixture = null;
  // JUnitDoclet end class
  
  public WikiTableSetupFixtureTest(String name) {
    // JUnitDoclet begin method WikiTableSetupFixtureTest
    super(name);
    // JUnitDoclet end method WikiTableSetupFixtureTest
  }
  
  public com.plexobject.testplayer.fitnesse.WikiTableSetupFixture createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.fitnesse.WikiTableSetupFixture();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    wikitablesetupfixture = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    wikitablesetupfixture = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testBegin() throws Exception {
    // JUnitDoclet begin method begin
    // JUnitDoclet end method begin
  }
  
  public void testEnd() throws Exception {
    // JUnitDoclet begin method end
    // JUnitDoclet end method end
  }
  
  public void testNodeValue() throws Exception {
    // JUnitDoclet begin method nodeValue
    // JUnitDoclet end method nodeValue
  }
  
  public void testValue() throws Exception {
    // JUnitDoclet begin method value
    // JUnitDoclet end method value
  }
  
  public void testAttributeValue() throws Exception {
    // JUnitDoclet begin method attributeValue
    // JUnitDoclet end method attributeValue
  }
  
  public void testGetObject() throws Exception {
    // JUnitDoclet begin method getObject
    // JUnitDoclet end method getObject
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(WikiTableSetupFixtureTest.class);
    // JUnitDoclet end method testcase.main
  }
}
