package com.plexobject.testplayer.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.util.CodeHelper;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CodeHelperTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.util.CodeHelper codehelper = null;
  // JUnitDoclet end class
  
  public CodeHelperTest(String name) {
    // JUnitDoclet begin method CodeHelperTest
    super(name);
    // JUnitDoclet end method CodeHelperTest
  }
  
  public com.plexobject.testplayer.util.CodeHelper createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return null;
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testDeclare() throws Exception {
    // JUnitDoclet begin method declare
    // JUnitDoclet end method declare
  }
  
  public void testGetPackageName() throws Exception {
    // JUnitDoclet begin method getPackageName
    // JUnitDoclet end method getPackageName
  }
  
  public void testGetTypeWithoutPackage() throws Exception {
    // JUnitDoclet begin method getTypeWithoutPackage
    // JUnitDoclet end method getTypeWithoutPackage
  }
  
  public void testGetBasicTypeWithoutPackage() throws Exception {
    // JUnitDoclet begin method getBasicTypeWithoutPackage
    // JUnitDoclet end method getBasicTypeWithoutPackage
  }
  
  public void testReadLines() throws Exception {
    // JUnitDoclet begin method readLines
    // JUnitDoclet end method readLines
  }
  
  public void testWriteLines() throws Exception {
    // JUnitDoclet begin method writeLines
    // JUnitDoclet end method writeLines
  }
  
  public void testSplit() throws Exception {
    // JUnitDoclet begin method split
    // JUnitDoclet end method split
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CodeHelperTest.class);
    // JUnitDoclet end method testcase.main
  }
}
