package com.plexobject.testplayer.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.util.ReflectHelper;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ReflectHelperTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.util.ReflectHelper reflecthelper = null;
  // JUnitDoclet end class
  
  public ReflectHelperTest(String name) {
    // JUnitDoclet begin method ReflectHelperTest
    super(name);
    // JUnitDoclet end method ReflectHelperTest
  }
  
  public com.plexobject.testplayer.util.ReflectHelper createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.util.ReflectHelper();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    reflecthelper = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    reflecthelper = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testInvoke() throws Exception {
    // JUnitDoclet begin method invoke
    // JUnitDoclet end method invoke
  }
  
  public void testHasMethod() throws Exception {
    // JUnitDoclet begin method hasMethod
    // JUnitDoclet end method hasMethod
  }
  
  public void testReadPrimitiveArray() throws Exception {
    // JUnitDoclet begin method readPrimitiveArray
    // JUnitDoclet end method readPrimitiveArray
  }
  
  public void testReadArray() throws Exception {
    // JUnitDoclet begin method readArray
    // JUnitDoclet end method readArray
  }
  
  public void testGetField() throws Exception {
    // JUnitDoclet begin method getField
    // JUnitDoclet end method getField
  }
  
  public void testWriteField() throws Exception {
    // JUnitDoclet begin method writeField
    // JUnitDoclet end method writeField
  }
  
  public void testReadField() throws Exception {
    // JUnitDoclet begin method readField
    // JUnitDoclet end method readField
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ReflectHelperTest.class);
    // JUnitDoclet end method testcase.main
  }
}
