package com.plexobject.testplayer.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.util.StringHelper;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class StringHelperTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.util.StringHelper stringhelper = null;
  // JUnitDoclet end class
  
  public StringHelperTest(String name) {
    // JUnitDoclet begin method StringHelperTest
    super(name);
    // JUnitDoclet end method StringHelperTest
  }
  
  public com.plexobject.testplayer.util.StringHelper createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new com.plexobject.testplayer.util.StringHelper();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    stringhelper = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    stringhelper = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testReplace() throws Exception {
    // JUnitDoclet begin method replace
    // JUnitDoclet end method replace
  }
  
  public void testSplit() throws Exception {
    // JUnitDoclet begin method split
    // JUnitDoclet end method split
  }
  
  public void testFsplit() throws Exception {
    // JUnitDoclet begin method fsplit
    // JUnitDoclet end method fsplit
  }
  
  public void testJoin() throws Exception {
    // JUnitDoclet begin method join
    // JUnitDoclet end method join
  }
  
  public void testCamel() throws Exception {
    // JUnitDoclet begin method camel
    // JUnitDoclet end method camel
  }
  
  public void testUncamel() throws Exception {
    // JUnitDoclet begin method uncamel
    // JUnitDoclet end method uncamel
  }
  
  public void testCountLetter() throws Exception {
    // JUnitDoclet begin method countLetter
    // JUnitDoclet end method countLetter
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(StringHelperTest.class);
    // JUnitDoclet end method testcase.main
  }
}
