package com.plexobject.testplayer.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.plexobject.testplayer.util.TypeHelper;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class TypeHelperTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.plexobject.testplayer.util.TypeHelper typehelper = null;
  // JUnitDoclet end class
  
  public TypeHelperTest(String name) {
    // JUnitDoclet begin method TypeHelperTest
    super(name);
    // JUnitDoclet end method TypeHelperTest
  }
  
  public com.plexobject.testplayer.util.TypeHelper createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return null;
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testIsPrimitive() throws Exception {
    // JUnitDoclet begin method isPrimitive
    // JUnitDoclet end method isPrimitive
  }
  
  public void testIsPrimitiveWrapper() throws Exception {
    // JUnitDoclet begin method isPrimitiveWrapper
    // JUnitDoclet end method isPrimitiveWrapper
  }
  
  public void testGetPrimitiveArrayMethod() throws Exception {
    // JUnitDoclet begin method getPrimitiveArrayMethod
    // JUnitDoclet end method getPrimitiveArrayMethod
  }
  
  public void testGetPrimitiveWrapper() throws Exception {
    // JUnitDoclet begin method getPrimitiveWrapper
    // JUnitDoclet end method getPrimitiveWrapper
  }
  
  public void testGetMethodCount() throws Exception {
    // JUnitDoclet begin method getMethodCount
    // JUnitDoclet end method getMethodCount
  }
  
  public void testIsPrimitiveArray() throws Exception {
    // JUnitDoclet begin method isPrimitiveArray
    // JUnitDoclet end method isPrimitiveArray
  }
  
  public void testIsPrimitiveWrapperArray() throws Exception {
    // JUnitDoclet begin method isPrimitiveWrapperArray
    // JUnitDoclet end method isPrimitiveWrapperArray
  }
  
  public void testIsArray() throws Exception {
    // JUnitDoclet begin method isArray
    // JUnitDoclet end method isArray
  }
  
  public void testIsCollection() throws Exception {
    // JUnitDoclet begin method isCollection
    // JUnitDoclet end method isCollection
  }
  
  public void testGetPrimitiveArrayType() throws Exception {
    // JUnitDoclet begin method getPrimitiveArrayType
    // JUnitDoclet end method getPrimitiveArrayType
  }
  
  public void testHasStringConstructor() throws Exception {
    // JUnitDoclet begin method hasStringConstructor
    // JUnitDoclet end method hasStringConstructor
  }
  
  public void testGetStringConstructor() throws Exception {
    // JUnitDoclet begin method getStringConstructor
    // JUnitDoclet end method getStringConstructor
  }
  
  public void testSetField() throws Exception {
    // JUnitDoclet begin method setField
    // JUnitDoclet end method setField
  }
  
  public void testFixType() throws Exception {
    // JUnitDoclet begin method fixType
    // JUnitDoclet end method fixType
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(TypeHelperTest.class);
    // JUnitDoclet end method testcase.main
  }
}
